version: '2.1'
services:
  server-dev:
    image: spotify-radio-js
    build: .
    environment:
      PORT: 3000
    command: 
      - npm
      - run
      - start:dev
    volumes:
        - .:/spotify-radio-js
        - node_modules:/spotify-radio-js/node_modules
    ports:
      - 3000:3000

volumes:
  node_modules: {}